version: 2.1
jobs:
  build:
    docker:
      - image: maven # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: mvn test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/testng/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/testng/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/testng
